### PR TITLE
Driver Service Fix Additions

### PR DESCRIPTION
**Pull request by goosewobbler**

### CODE REVIEW

**Comment by christian-bromann** [comment]
@goosewobbler please note that I continued working on your PR over the last days

**Comment by christian-bromann** [comment]
Oh, now I see it is a PR to it. Taking a look 👀

**Review by christian-bromann — APPROVED** [review]
LGTM 👍 

Feel free to continue work on the other branch. I will continue to do so as well tonight. I don't think it is much to do at this point.

Also, would you be available for a call? I am speaking at FinOSS on Electron Testing with WebdriverIO and need to pick your brain.

**Comment by goosewobbler** [comment]
Yeah, I think it's getting there.  My local builds are passing now and my local repo should be reflected in this PR, CI still having issues, doesn't seem to be a consistent test failing - I've had everything from 3 passes 1 failure to 1 pass 3 failures...

Happy to do a call, shall I pick a slot on the Open Office Hours Calendly?

**Comment by christian-bromann** [comment]
> shall I pick a slot on the Open Office Hours Calendly?

That would be awesome, thanks!

If it helps to debug the build, try https://github.com/stateful/vscode-server-action which allows you to open VS Code within the machine that runs in CI: https://github.com/stateful/vscode-server-action

**Pull request merged**
