### PR TITLE
Driver Service Fix

### PR DESCRIPTION
**Pull request by goosewobbler**
Updating the service for the breaking changes released with WDIO v8.14.0:

* Removed dependency on `wdio-chromedriver-service`
* WDIO now handles Chromedriver download and processes
* Improved capabilities mapping, parity with other services
* Parallel Multiremote supported
* Service options moved into capabilities
* Updated all dependencies
* Improved debugging using `debug`
* Replaced appPath / appName / binaryPath with appBinaryPath to reduce complexity
* New getBinaryPath helper from wdio-electron-service/utils to assist users of appPath / appName
* Restructured examples
  * app used by ESM example is now also ESM - using Electron 28 (currently nightly)
  * using Rollup instead of Webpack
* CJS build now using symlinks instead of files with a single require()

TODO:
- [x] Extract & rework capabilities mapping
  - [x] Ensure the service works with [parallel multiremote](https://github.com/webdriverio/webdriverio/pull/10803) released in WDIO v8.15.0
  - [x] Fix type handling
  - [x] Add / update unit tests
- [x] Use custom electron to chromium version map based on [`electron-to-chromium`](https://github.com/kilian/electron-to-chromium) for delegating CD download to WDIO
  - [x] Add / update unit tests
- [x] Fix Linux & Mac integration b0rkage
- [x] Fix WDIO CD spawn errors
- [x] Fix WDIO CD download flakiness
- [x] Remove service-managed CD download
- [x] Remove chromedriverCustomPath in favour of user setting `wdio:chromedriverOptions` directly
- [x] Move service options into capabilities
- [x] Update unit tests
- [x] Fix linting
- [x] Update docs

### CODE REVIEW

**Comment by goosewobbler** [comment]
@christian-bromann So, [@electron/get](https://www.npmjs.com/package/@electron/get) is the way we were downloading Chromedriver, I am not sure we can use it to get the CD version string in order to pass it to WDIO as it is designed to abstract this process and download the appropriate assets for a given electron version.  Since WDIO itself is now handling the download, perhaps the best way forward here is to amend the WDIO download logic to use `@electron/get` when an electronVersion (as passed by this service) value is provided.

**Comment by christian-bromann** [comment]
I think there are two approaches we can go:

1. keep the launcher and use `@electron/get` to download Chromedriver - then in the launcher set the following capabilities:
    ```ts
    'wdio:chromedriverOptions': { binary: '/path/to/chromedriver' },
    'goog:chromeOptions: { binary: '/path/to/electron/app' }
    ```
2. get the Chromedriver version based on the Electron version and update the capabilities as part of the launcher so that WebdriverIOs driver manager handles the download

Wdyt?

**Comment by goosewobbler** [comment]
@christian-bromann I prototyped the first approach and it's not able to connect to Chromedriver when specifying the hostname / port.  Is there anything obvious I could have missed?

**Comment by christian-bromann** [comment]
@goosewobbler the port `9519` doesn't seem to be correct, can you remove it from the configuration? WebdriverIO will find a port for you.

**Comment by goosewobbler** [comment]
Hmmm, that didn't work, it's now trying to connect to `http://localhost:undefined/`

**Comment by christian-bromann** [comment]
Can you check that you don't set any of these options in the service: `hostname`, `port`, `path` or `protocol`?

**Comment by goosewobbler** [comment]
After a bit of investigation I'm still not sure why windows builds are passing when the other two platforms fail, I will focus on getting the capabilities mapping right before doing anything else though.

**Comment by christian-bromann** [comment]
> [move appArgs to capabilities](https://github.com/webdriverio-community/wdio-electron-service/pull/168/commits/03bcb5f8d4902630a6128526858983b58cb2660e)

Do you think it makes sense to move more electron service options to the capability section? It looks to me like a better approach to define these things there, e.g. the VS Code service wants you to define your caps like this:

```ts
    capabilities: [{
        browserName: 'vscode',
        browserVersion: '1.71.0', // "insiders" or "stable" for latest VSCode version
        'wdio:vscodeOptions': {
            extensionPath: __dirname,
            userSettings: {
                "editor.fontSize": 14
            }
        }
    }],
    services: ['vscode'],
```

That said, it probably requires more rewrite and might be something we can tackle later after we got the service running with latest version again.

Let me know if I can help you in anything. To debug the GitHub action I recommend using https://github.com/stateful/vscode-server-action to debug.

**Comment by goosewobbler** [comment]
I think it does make sense, additionally I suspect the integration tests are broken because of some changes in this area so I started moving things over to the way the VS Code service handles things.

I have a couple of questions:

* Prior to this work we were setting capabilities in the service `beforeSession`.  Now we are setting capabilities in the launcher `onPrepare`, do they need to be set in both places?
* Should I move over every setting and just leave the ServiceOptions as an empty object?

```
export interface ElectronCapabilities extends Capabilities.Capabilities {
  'wdio:electronOptions': {
    appName?: string;
    appPath?: string;
    binaryPath?: string;
    customApiBrowserCommand?: string;
    chromedriverCustomPath?: string;
  };
}
```

**Comment by goosewobbler** [comment]
Also, I prototyped using [electron-to-chromium](https://github.com/kilian/electron-to-chromium) for delegating the Chromedriver download to WDIO, but I'm not really sure of the benefit of this vs. the other approach using `@electron/get` to download directly.  As far as I can see, the only real benefit is less code in the service due to the download being managed by WDIO.  The downsides of using E2C are that it's not maintained by the Electron team, and that we have to update the version mapping list - either by calling the [build / update script](https://github.com/kilian/electron-to-chromium#updating) or with a download of [the JSON file](https://raw.githubusercontent.com/Kilian/electron-to-chromium/master/full-versions.json) from the github repo.

We could use one approach as a fallback for the other, but I'm not sure that level of redundancy is required.

**Comment by christian-bromann** [comment]
@goosewobbler just a heads up, I will pick this up as I will speak about Electron testing in November: https://sched.co/1Q1Fa

**Comment by goosewobbler** [comment]
@christian-bromann Nice, I haven't had much time for this unfortunately.  I like the updates, a few things in there which I've been meaning to get to and better standardisation with the other services.  I just created another [PR](#168) to see if I can fix the build.  Locally the E2E app is running but the tests stalling.  I'm wondering if the CD process handling in WDIO is the issue here as on CI there are spawn errors... 

https://github.com/webdriverio-community/wdio-electron-service/actions/runs/6324183608/job/17173519370#step:6:889

**Comment by goosewobbler** [comment]
Added debug and merged in, seeing a lot of 404s for this:

https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.190/linux64/chromedriver-linux64.zip

I don't think it's critical though, unlike the spawn errors which seem to correlate with the failed specs.  Annoyingly it's not letting me look at the debug step output until after the timeout.

**Comment by christian-bromann** [comment]
@goosewobbler I see now .. yeah if you run multiple workers in parallel and they all try to setup the same driver at the same location there are race conditions. In the core project we therefore have another set up in the [CLI launcher](https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-cli/src/launcher.ts#L138-L144) which maps all driver and browser into a flat list and configures them for all workers. This means we have to move this logic into the `onPrepare` hook.

**Comment by goosewobbler** [comment]
@christian-bromann You mean move that mapping into onPrepare?  Surely that's happening immediately after onPrepare so moving it won't make much difference...  I tried it anyway: 
https://github.com/webdriverio-community/wdio-electron-service/pull/193/files

**Comment by christian-bromann** [comment]
Sorry for not being clear. I meant moving the process of updating the capabilities into the `onPrepare` hook. By changing the values in these objects we can leverage from the driver setup in the CLI launcher process. I think we are at a good state with this. Let me know if you think anything is missing. I suggest to release this as major version upgrade.

**Comment by goosewobbler** [comment]
Nice, thanks for the updates, it's much closer to being ready now.  While we're major bumping (this PR already targetting 5.0.0 milestone) I looked to replace the `appName` / `appPath` approach to configuration with `appBinaryPath`, it simplifies things a lot.  The old approach only worked for electron-builder users;  I moved it to a `getBinaryPath` util which works in ESM, not sure why it's failing in CJS.  If I can't get that import working then I'll just hard code the util in the examples and reference it in the docs.  

I also made some tweaks to the unit tests, PR for this work [here](#196).

**Comment by christian-bromann** [comment]
@goosewobbler let me know if there is anything left to do to land this. Amazing work!

**Comment by goosewobbler** [comment]
@christian-bromann Thanks!  With that latest PR I think it's done.  Will run a couple of smoke tests with an external repo before release.

**Comment by christian-bromann** [comment]
Awesome, please feel free to merge and release as major change anytime you are ready.

**Comment by christian-bromann** [comment]
Awesome work 🎉

**Pull request merged**
