### PR TITLE
(feat): add appEntryPoint for executing electron directly with a main script

### PR DESCRIPTION
**Pull request by goosewobbler**
Prototyping the feature proposed in #331.

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
This is awesome 🎉  I will make a PR to the config wizard to have this be the default behavior.

**Comment by goosewobbler** [comment]
It will be awesome once it works 🤣  It's running electron but not managing to load the window.  Loading manually with e.g. `./example-no-binary/node_modules/.bin/electron --app=./example-no-binary/dist/main.bundle.js` loads the app fine...

**Comment by goosewobbler** [comment]
I don't currently have the time to investigate why this isn't working, currently focussing on the mocking rework.

**Comment by tanin47** [comment]
> but I can't see anything obviously causing this apart from perhaps the  data:, at the end...

You can change it by providing `appArgs = ['--user-data-dir=/tmp/test-chrome-2']` in `launcher.js`.

**Comment by goosewobbler** [comment]
Closing in favour of #545

**Pull request closed without merging**
