### PR TITLE
fix: spy import

### PR DESCRIPTION
**Pull request by goosewobbler**
Fixing the `@vitest/spy` require / import issue with a dynamic import and updating the E2Es so that future issues of this nature will be caught ahead of release.

### CODE REVIEW

**Comment by goosewobbler** [comment]
@christian-bromann the reproduction works and so does the fix but I would rather not add yet another example / E2E directory as each new one slows down the build significantly.  I am considering just removing rollup from the `example`, `example-cjs` and `example-electron-builder` directories, what do you think?

Also, I [switched to copy](https://github.com/webdriverio-community/wdio-electron-service/pull/421/commits/4a6b364b246e2064d4d6001c531a686c511421d3) the requisite files from the main (ESM) dir to `src/cjs` instead of symlinking them.  Do you have a preference for this or the previous method?

**Comment by christian-bromann** [comment]
> I am considering just removing rollup from the `example`, `example-cjs` and `example-electron-builder` directories, what do you think?

I think that makes sense. If the examples are plain JS files that is fine.

> Do you have a preference for this or the previous method?

No preference 👍

**Comment by goosewobbler** [comment]
Update here, removing bundling from the ESM example dirs proved tricky so I just removed it from `example-cjs`.  The E2Es pass now but the mock units are still broken.

**Review by christian-bromann — APPROVED** [review]
Awesome 👍

**Pull request merged**
