### PR TITLE
delegate chromedriver version management to users

### PR DESCRIPTION
**Pull request by goosewobbler**
Making electron-chromedriver an optional peerdep, looking for it when chromedriverCustomPath is not specified, throwing an error when not found.

- [x] impl
- [x] docs
- [x] manual tests - electron-chromedriver, chromedriver, error case
- [x] update example repo

### CODE REVIEW

**Comment by christian-bromann** [comment]
Is there a way to detect the Chromium version based on the Electron version used? I had similar issues when working on the [VSCode test service](https://github.com/webdriverio-community/wdio-vscode-service/blob/main/src/launcher.ts). Maybe we can hardcode a list of Chromedriver versions that are compatible to a specific Electron version.

Overall it would be nice if this service can help with the whole Chromedriver setup in some way or the other.

**Comment by goosewobbler** [comment]
@christian-bromann I'm not sure. Obviously there is a mapping between Chromium version and Electron version but I'm not sure we can get either for a given app without running it and/or doing something crazy:

https://stackoverflow.com/questions/50345957/how-to-display-version-of-electron-environment-in-an-electron-app

It would be nice to do something else though if it is possible to find the Electron version, even if it's just a command prompt to install a specific version of `electron-chromedriver`.

**Comment by christian-bromann** [comment]
@goosewobbler sounds good! How about we assume by default the user wants to test the latest Electron version and if not and an older version is being tested, that version needs to be specified in the capabilities. You can define your custom ones, e.g.: `wdio:electronService: { electronVersion: "..." }` or something similar. Then you read it in the launcher and feed that value into `electron-chromedriver`.

**Comment by goosewobbler** [comment]
@christian-bromann any interaction with `electron-chromedriver` would have to be around the npm setup / install stage...it just downloads and installs the appropriate chromedriver package for your setup and specified electron version, I think just selecting a package from e.g. https://registry.npmmirror.com/binary.html?path=electron/16.0.0/ for v16.  Installing the latest version gives you the chromedriver version for the latest version of electron.

https://github.com/electron/chromedriver

Could read the wdio config file as part of a setup script to ensure the right chromedriver version but it would need to be done separately from the launcher execution I reckon.

**Comment by christian-bromann** [comment]
What I've did in the VSCode service is that as part of the launcher I would download the required Chromedriver version and put it into a `.vscode-service` directory. It seems like `electron-chromedriver` is not ideal for the task of downloading Chromedriver here, given it has no interface to do that during the launch process. I think there are two tasks at hand:

1. find the dedicated Chromedriver version for the Electron version that is suppose to be tested: a solution for this can be a hardcoded list
2. download Chromedriver during the launch process: I suggest to use the [`download`](https://www.npmjs.com/package/download) package and pull it from https://chromedriver.storage.googleapis.com/ , an example of this implementation can be found [here](https://github.com/webdriverio-community/wdio-vscode-service/blob/main/src/launcher.ts#L119-L151)

What do you think?

**Comment by goosewobbler** [comment]
Sounds good, I'll raise a separate ticket for this as it's a fair bit more involved than this stopgap approach. Basically taking electron-chromedriver and pulling it into the service. Can use https://github.com/electron/get for this I think.

**Pull request merged**
