### PR TITLE
ci: Add Expense Contribution workflow

### PR DESCRIPTION
**Pull request by seanpoulter**
### Proposed Changes

- Add workflow from [webdriverio/expense-action](https://github.com/webdriverio/expense-action)

### CODE REVIEW

**Review by goosewobbler — APPROVED** [review]
LGTM, formatting needs fixing - I use the VSCode prettier extension and format on save but for everyone else prettier should be running on pre-commit as per the docs - did you run `init-dev` to set up husky?

https://github.com/webdriverio-community/wdio-electron-service/blob/main/docs/development.md#formatting

EDIT: we didn't update the scripts for husky v9, doing that [here](#446) - this should ensure husky will be running even if someone doesn't use `init-dev`, though obviously dependencies install is still required.

**Comment by seanpoulter** [comment]
> formatting needs fixing

@christian-bromann, any thoughts on how we plan to change the **Expense Contribution** workflow? Will we make repo-specific changes or will it be kept similar across repos?

--

Thanks for the review @goosewobbler. I did not run the formatting. Christian asked for help adding the workflow to all 42 public repositories in webdriverio and webdriverio-community. I pretty much did that using `cp` in a loop. If we want to keep things consistent, I'd advocate for adding a comment saying it is consistent and adding the workflow to `.prettierignore`.

**Comment by goosewobbler** [comment]
I know Prettier isn't used across the other WDIO repos (I think it should be) but I think I'd rather consistency in the formatting of the workflows here.  In any case #446 should fix the case where someone is contributing from a local repo which has dependencies installed.  Contributing without installing deps, though it may have happened here, is a significantly less likely occurrence IMO.

Perhaps these shared workflows could be shared as an npm module?

**Comment by seanpoulter** [comment]
That's a great idea. I couldn't find a way to create a shared workflow. The [Sharing Workflows](https://docs.github.com/en/actions/using-workflows/sharing-workflows-secrets-and-runners-with-your-organization#sharing-workflows) docs provide two options:

* Reusing workflows - Call a common workflow from a workflow
* Use starter workflows - Create a template in the **{org}/.github** repo that can be configured to create a new commit in any repo

Unfortunately those don't provide a way to share the workflow_dispatch inputs.
Even if we extracting the two jobs as a reusable workflow or npm module we still end up needing to copy/paste. 😓

**Comment by christian-bromann** [comment]
> Could these shared workflows be shared and used as an npm module?

Happy for suggestions how we can simplify sharing this workflow across the org. Afaik the current shared action allows us to only have to commit the workflow. I was thinking of moving it into a `.github` org repo but according to @seanpoulter this doesn't work either. Let me know if you have other suggestions.

**Review by christian-bromann — APPROVED** [review]
LGTM 👍 

Let's ensure we have proper formatting according to this projects prettier rules.

**Comment by christian-bromann** [comment]
> I know Prettier isn't used across the other WDIO repos (I think it should be)

Thanks for the feedback. I am personally not a big fan of prettier as it creates more developer friction as it actually provides value. I am in happy to have strict eslint rules that includes formatting. That said, this is also just my opinion, happy to align to whatever we all thing is good moving forward.

**Comment by christian-bromann** [comment]
> Just the once, or use it everywhere? 🤔

Just in this repo for now until we have alignment to use prettier across the project or not.

**Comment by christian-bromann** [comment]
Thanks, let's :shipit:

**Comment by goosewobbler** [comment]
> Unfortunately those don't provide a way to share the workflow_dispatch inputs. Even if we extracting the two jobs as a reusable workflow or npm module we still end up needing to copy/paste. 😓

I suspected this might be the case... worth investigating anyway.

> I am personally not a big fan of prettier as it creates more developer friction as it actually provides value. I am in happy to have strict eslint rules that includes formatting. That said, this is also just my opinion, happy to align to whatever we all thing is good moving forward.

Personally I found it to reduce friction - once the (limited) config settings are agreed upon, the tooling does the work of standardising everything and then PRs are limited to discussion actual implementation, as opposed to tediously pointing out formatting nits...which I have experienced to a great degree in previous projects.  Also just my opinion 😄 

🚢

**Pull request merged**
