### PR TITLE
(feat): auto-updating mocks

### PR DESCRIPTION
**Pull request by goosewobbler**
Reworking mocking of electron APIs for a more [vitest-like experience](https://vitest.dev/api/mock.html), to be released in stages.

Tracking issue for remaining features: https://github.com/webdriverio-community/wdio-electron-service/issues/368

TODO:

- [x] Extract mock storage
- [x] Extract mock object (implements vitest `Mock`)
- [x] `mockImplementation`
- [x] `mockImplementationOnce`
- [x] `mockReturnValue`
- [x] `mockReturnValueOnce`
- [x] `mockRestore`
- [x] `mockReset`
- [x] `mockClear`
- [x] Update `mockAll`
- [x] Utilities
  - [x] [`clearAllMocks`](https://vitest.dev/api/vi.html#vi-clearallmocks)
  - [x] [`resetAllMocks`](https://vitest.dev/api/vi.html#vi-resetallmocks)
  - [x] `removeMocks` => [`restoreAllMocks`](https://vitest.dev/api/vi.html#vi-restoreallmocks)
- [x] Config options
  - [x] [`clearMocks`](https://vitest.dev/config/#clearmocks)
  - [x] [`resetMocks`](https://vitest.dev/config/#mockreset)
  - [x] [`restoreMocks`](https://vitest.dev/config/#restoremocks)
- [x] Units
- [x] Typedocs
- [x] Docs - split README
- [x] Docs - update electron APIs doc for mocking
- [x] E2Es for `clearAllMocks` and `restoreAllMocks`

### CODE REVIEW

**Comment by christian-bromann** [comment]
👏 can't wait for this to land, let me know if you are ready and need a review 😉

**Comment by goosewobbler** [comment]
@christian-bromann this is ready for review now...

**Review by christian-bromann — APPROVED** [review]
This is exceptional work 💯 thank you so much!

I reviewed the code and it looks all good to me. I am super excited to get this merged and release. I will see if I can find some time to maybe make another video about the mocking features. It deserves to be highlighted as no one else has this great DX for testing Electron apps so far.

I've reached out to you via email about this: I talked with the technical steering committee team and we agreed to (partially) reimburse you for all your work on the Electron service front. While it probably doesn't cover the time you spent on this project it is at least a small token of appreciation of your work. We hope to be able to pay out more soon. Please let me know your thoughts on that.

**Comment by christian-bromann** [comment]
FYI: I will work on a patch in the core project to auto-embed the great docs you put together into the main project page

**Comment by goosewobbler** [comment]
This is great, I'm pleased with how this turned out.  It's released now, I'm going to follow up with a few PRs to implement the remaining Vitest functionality documented in #368.  Will respond to the email, it slipped through the cracks...

**Pull request merged**
